### ISSUE TITLE
why is jquery code not responding

### ISSUE THREAD

**Issue by solomonotoo** [thymeleaf/thymeleaf#822]
Am trying to create sidebar menu in a thymleaf but I dont know what am missing. 
This is where am actually facing the problem main_layou.html file

main_layout.html
```html
<!DOCTYPE html>
<html xmlns:sec="http://www.thymeleaf.org/extras/spring-security">
<head>
<link rel="stylesheet" href="../../static/css/style.css"
	th:href="@{css/style.css}" />
<link rel="stylesheet" href="../../static/css/stylesidebar.css"
	th:href="@{css/stylesidebar.css}" />
<link th:rel="stylesheet"
	th:href="@{/webjars/font-awesome/5.15.2/css/all.css}">
<link th:rel="stylesheet"
	th:href="@{/webjars/bootstrap/4.5.0/css/bootstrap.min.css}">
<script type="text/javascript"
	th:src="@{/webjars/jquery/3.5.1/jquery.js}"></script>
<script type="text/javascript"
	th:src="@{/webjars/bootstrap/4.5.0/js/bootstrap.js}"></script>

<meta charset="ISO-8859-1">
<title>Insert title here</title>
</head>
<body>
	<div th:replace="fragments/header::header"></div>

	<div layout:fragment="content" class="container">

		<script type="text/javascript">
			$('.sidebar-btn').click(function() {
				$(this).toggleClass("click");
				$('.sidebar').toggleClass("show");
			})
			$('.feat-btn').click(function() {
				$('nav ul .feat-show').toggleClass("show");
				$('nav ul .first').toggleClass("rotate");
			});
			$('.serv-btn').click(function() {
				$('nav ul .serv-show').toggleClass("show1");
				$('nav ul .second').toggleClass("show");
			});
			$('nav ul li').click(function() {
				$(this).addClass("active").siblings().removeClass("active");
			});
		</script>
	</div>

	<div th:replace="fragments/footer::footer"></div>
</body>
</html>
```

Below is the other files 
header.html file
```html
<header>
	 <div class="header">
		<div class="header-menu">
			<div class="title">
				ECC<span>Soft</span>
			</div>
			<div class="sidebar-btn">
				<span class="fas fa-bars"></span>
				<!--icon -->
			</div>
			<ul>
				<li><a href="#"><i class="fas fa-search"></i></a></li>
				<!--icon -->
				<li><a href="#"><i class="fas fa-bell"></i></a></li>
				<!--icon -->
				<li><a href="#"><i class="fas fa-power-off"></i></a></li>
				<!--icon -->
			</ul>
		</div>
	</div>
	<nav class="sidebar">
		<ul>
			<li><a href="#">Dashboard</a></li>
			<li><a href="#" class="feat-btn">Features <span
					class="fas fa-caret-down first"></span>
			</a>
				<ul class="feat-show">
					<li><a href="#">Pages</a></li>
					<li><a href="#">Elements</a></li>
				</ul></li>
			<li><a href="#" class="serv-btn">Services <span
					class="fas fa-caret-down second"></span>
			</a>
				<ul class="serv-show">
					<li><a href="#">App Design</a></li>
					<li><a href="#">Web Design</a></li>
				</ul></li>
			<li><a href="#">Portfolio</a></li>
			<li><a href="#">Overview</a></li>
			<li><a href="#">Shortcuts</a></li>
			<li><a href="#">FeedBack</a></li>
		</ul>
	</nav>
</header>
```

index.html file

```html
<!DOCTYPE html>
<html xmlns:th="http://www.thymeleaf.org"
	xmlns:layout="http://www.ultraq.net.nz/thymeleaf/layout"
	layout:decorate="~{fragments/main_layout}">
<head>
<meta charset="ISO-8859-1">
<title>Insert title here</title>
</head>
<body>
	<div layout:fragment="content" class="container">
	        <div class="main-container">
			<div class="card">
				<p>Thanks for using ecc soft</p>
                        </div>
		</div> 
	</div>
</body>
</html>
```

css file

```css
*{
  margin: 0;
  padding: 0;
  user-select: none;
  box-sizing: border-box;
  font-family: 'Poppins', sans-serif;
  list-style: none;
}
/* .sidebar-btn{
  position: absolute;
  top: 15px;
  left: 45px;
  height: 45px;
  width: 45px;
  text-align: center;
  background: #1b1b1b;
  border-radius: 3px;
  cursor: pointer;
  transition: left 0.4s ease;
} */
/* .sidebar-btn.click{
  left: 260px;
} */
/* .btn span{
  color: white;
  font-size: 28px;
  line-height: 45px;
} */
.sidebar-btn.click span::before{
  content: '\f00d';
}
.sidebar{
  position: fixed;
  width: 250px;
  height: 100%;
  left: -250px;
  background: #1b1b1b;
  transition: left 0.4s ease;
}
.sidebar.show{
  left: 0px;
}

.sidebar .text{
  color: white;
  font-size: 25px;
  font-weight: 600px;
  line-height: 65px;
  text-align: center;
  background: #1e1e1e;
  letter-spacing: 1px;
}

nav ul{
  background: #1b1b1b;
  height: 100%;
  width: 100%;
  list-style: none;;
}

nav ul li{
  line-height: 60px;
  border-bottom: 1px solid rgba(255,255,255,0.1);
}
nav ul li:last-child{
  border-bottom: 1px solid rgba(255,255,255,0.1);
}
nav ul li a{
  position: relative;
  color: white;
  text-decoration: none;
  font-size: 180x;
  padding-left: 40px;
  font-weight: 500;
  display: block;
  width: 100%;
  border-left: 3px solid transparent;
}

nav ul li.active a{
  color: cyan;
  background: #1e1e1e;
  border-left-color: cyan;
}

nav ul ul{
  position: static;
  display: none;
}
nav ul .feat-show.show{
  display: block;
}
nav ul .serv-show.show1{
  display: block;
}
nav ul ul li{
  line-height: 42px;
  border-bottom: none;
}
nav ul ul li a{
  font-size: 17px;
  color: #e6e6e6;
  padding-left: 80px;
}
nav ul li.active ul li a{
  color: #e6e6e6;
  background: #1b1b1b;
  border-left-color: transparent;
}
nav ul ul li a:hover{
  color: cyan!important;
  background: #1e1e1e!important;
}
nav ul li a span{
  position: absolute;
  top: 50%;
  right: 20px;
  transform: translateY(-50%);
  font-size: 22px;
  transition: transform 0.4s;
}

nav ul li a span.rotate{
  transform: translateY(-50%) rotate(-180deg);

}

.header .header-menu ul{
	display: flex;
}
 .header .header-menu ul li a{
	background: #fff;
	color: #000;
	display: block;
	margin: 0 10px;
	font-size: 18px;
	width: 34px;
	height: 34px;
	line-height: 35px;
	text-align: center;
	border-radius: 50%;
	transition: 0.3s;
	transition-property: background, color;

}
.header .header-menu ul li a:hover{
	background: #4CCEEB;
	color: #fff;
}
.header .header-menu .sidebar-btn:hover{

	color: #4CCEE8;
}
 .header{
	z-index: 1;
	background: #22242A;
	position: fixed;
	width: calc(100% - 0%);
	height: 70px;
	display: flex;
	top: 0;
}

.header .header-menu{

	width: calc(100% - 0%);
	height: 100%;
	display: flex;
	justify-content: space-between;
	align-items: center;
	padding: 0 20px;
}
.header .header-menu .title{
	color: #fff;
	font-size: 25px;
	text-transform: uppercase;
	font-weight: 900;

}

.header .header-menu .title span{
	color: #4CCEEB;
}

 .header .header-menu .sidebar-btn{
	color: #fff;
	position: absolute;
	margin-left: 240px;
	font-size: 22px;
	font-weight: 900;
	cursor:pointer;
	transition: 0.3s;
	transition-property: color
}
.header .header-menu .sidebar-btn:hover{

	color: #4CCEE8;
}
```
