### ISSUE TITLE
IllegalArgumentException when upgrade from 3.1.0.M3 to 3.1.0.RC1 and forward-headers-strategy: framework

### ISSUE THREAD

**Issue by ftonik** [thymeleaf/thymeleaf#926]
I try Spring Boot 3(RC2). We have simple app.(https://github.com/ftonik/sb3-thymleaf)
All works fine in development mode. But when I try deploy in production with enabled **_server.forward-headers-strategy: framework_** propery it caused IllegalArgumentException([exception.txt](https://github.com/thymeleaf/thymeleaf/files/10021542/exception.txt))
Nginx ingress configuration:
```
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: hello-app
  labels:
    app: hello-app
  annotations:
    nginx.ingress.kubernetes.io/force-ssl-redirect: "true"
    nginx.ingress.kubernetes.io/rewrite-target: /$2
    nginx.ingress.kubernetes.io/x-forwarded-prefix: /hello-app/master
spec:
  ingressClassName: nginx
  tls:
  - hosts:
    - test.com
    secretName: test.com-tls
  rules:
  - host: test.com
    http:
      paths:
      - path: /hello-app/master(/|$)(.*)
        pathType: ImplementationSpecific
        backend:
          service:
            name: hello-app
            port:
              number: 80
```

If I rollback thymleaf dependency to _**org.thymeleaf:thymeleaf:3.1.0.M3**_ it works correct.
Seems that problem appear after that [commit](https://github.com/thymeleaf/thymeleaf/commit/3d1f0dd11e9b984640bc120c11f7f0e0f183af95). 
But it is not clear what I should do to fix this exception
