### ISSUE TITLE
get unexpect result contend like "&#x3053;&#x3093;&#x306b" when use UTF-8 encoding in the version above org.thymeleaf.spring4

### ISSUE THREAD

**Issue by RookieWutongshu** [thymeleaf/thymeleaf#946]
hi
 here is something stange that when you try to get some result content after use springTemplateEngine.process().
 In the version in the 1.4.3.RELEASE, It can print the correct result. but use a newer version with the class org.thymeleaf.spring5  or  org.thymeleaf.spring6 ,it will get some strange string result like "&#x3053;&#x3093;&#x306b".  Is there any configuration I need to configure in a later version

here is the code that can reproduce the problem
```java
package com.demo.test;

import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.scheduling.annotation.Scheduled;
import org.springframework.stereotype.Component;
import org.thymeleaf.context.Context;
import org.thymeleaf.spring6.SpringTemplateEngine;
import java.util.HashMap;
import java.util.Map;

@Component
public class ThymeleafDemo1 {
    @Autowired
    SpringTemplateEngine springTemplateEngine;

    @Scheduled( cron = "0/5 * * * * ?")
    public void process() {
        Map<String, String> pinfo = new HashMap<>();
        Context context = new Context();
        context.setVariable("pinfo", pinfo);
        pinfo.put("English", "hello world");
        pinfo.put("Russian", "Привет, мир.");
        pinfo.put("Japanese", "こんにちは、世界です");
        pinfo.put("Chinese", "你好,世界");
        pinfo.put("Korean", "안녕, 세계");
        String content = springTemplateEngine.process("demo1", context);
        System.out.println(content);
    }
}
```

which the demo1 template is 

```xml
<?xml version = "1.0" encoding = "UTF-8"?>
<language>
    <English th:text="${pinfo['English']}"></English>
    <Janpanese th:text="${pinfo['English']}"></Janpanese>
    <Russian th:text="${pinfo['Russian']}"></Russian>
    <Japanese th:text="${pinfo['Japanese']}"></Japanese>
    <Chinese th:text="${pinfo['Chinese']}"></Chinese>
    <Korean th:text="${pinfo['Korean']}"></Korean>
</language>
```

when i use the spring-boot-starter-thymeleaf version 3.0.2 with jdk19, it return garbled code

![image](https://user-images.githubusercontent.com/34189647/219133190-82719941-e124-48e9-85b9-d4c84e86f4cf.png)

when i use the spring-boot-starter-thymeleaf version 1.4.3.RELEASE with jdk 8 , it return what i expected

![image](https://user-images.githubusercontent.com/34189647/219134420-7eca98a6-9ebd-4c01-a7fc-19813caaaf92.png)

here is my config file ,I had already config the encoding, But it doesn't seem to work in the newer version 
```yaml
[thymeleaf-demo.zip](https://github.com/thymeleaf/thymeleaf/files/10746817/thymeleaf-demo.zip)
[thymeleaf-demo.zip](https://github.com/thymeleaf/thymeleaf/files/10746828/thymeleaf-demo.zip)

spring:
  thymeleaf:
    cache: false
    prefix: classpath:/templates/
    suffix: .xml
    encoding: UTF-8
    content-type: text/xml

```
